name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Download Spigot Buildtools
      run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && tree
    - name: Build
      run: java -Xms2G -jar BuildTools.jar -rev 1.19.2
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
          path: ./
